# File Tree: edupay-africa

**Generated:** 3/18/2026, 12:50:07 PM
**Root Path:** `c:\xampp\htdocs\edupay-africa`

```
├── 📁 config
│   └── 🐘 db.php
├── 📁 database
│   └── 📄 schema.sql
├── 📁 public
│   ├── 📁 css
│   │   └── 🎨 style.css
│   ├── 📁 js
│   │   └── 📄 main.js
│   ├── 🐘 add_institution.php
│   ├── 🐘 dashboard.php
│   ├── 🐘 index.php
│   ├── 🐘 login.php
│   ├── 🐘 logout.php
│   ├── 🐘 register.php
│   └── 🐘 view_fees.php
├── 📁 src
│   ├── 🐘 Institution.php
│   ├── 🐘 User.php
│   └── 🐘 logout.php
├── 📁 utils
│   └── 🐘 hash_tool.php
├── ⚙️ .htaccess
├── 📄 LICENSE
└── 📝 README.md
```

---
*Generated by FileTree Pro Extension*